### ISSUE TITLE
[Second sprint - abstract] Better way to display the order-cancelation period ending

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#131]
tbd

**Comment by gabitoesmiapodo** [comment]
Maybe we can close this one?

**Comment by gabitoesmiapodo** [comment]
@josojo probably we can close this one, we are already showing the last order cancelation date and there's also an update to that here https://www.figma.com/file/hapgMbgd2Zo5NFZDNfbogQ/Gnosis-Auction-Feedback?node-id=501%3A2
