### ISSUE TITLE
[Second sprint - abstract] UI support for concept of a minimum funding for auctions

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#132]
Auctions will only be settled, if the minimum funding is reached

**Comment by gabitoesmiapodo** [comment]
@josojo 

Added some ideas here https://www.figma.com/file/hapgMbgd2Zo5NFZDNfbogQ/Gnosis-Auction-Feedback?node-id=501%3A2

**Comment by gabitoesmiapodo** [comment]
Design here: https://zpl.io/b6KvD5m

I will implement the overall visual style on https://github.com/gnosis/ido-ux/issues/152 but we can use this issue to implement the logic for the "minimum funding" field.

**Comment by gabitoesmiapodo** [comment]
Will be implemented on #526
