### ISSUE TITLE
Add more auction information

### ISSUE THREAD

**Issue by cmagan** [gnosis/ido-ux#152]
In order to better provide information to the user about the current status of the auction, I propose to add a small section with these details:

- Current estimated price
- Current estimated funds raised
- Current estimated tokens sold (could also be implemented as a progress bar)

I'm not sure where is the appropriate place to add this.
One solution is to add this instead of the chart, and move the chart into a modal so users on see it on a much larger scale.
What are your thoughts?

**Comment by gabitoesmiapodo** [comment]
@cmagan @Rafanator @josojo 

I uploaded some new designs to Figma https://www.figma.com/file/hapgMbgd2Zo5NFZDNfbogQ/Gnosis-Auction-Feedback?node-id=501%3A2

You can leave your comments there.

**Comment by gabitoesmiapodo** [comment]
Design here https://zpl.io/2j3kX5Q / https://zpl.io/b6KvD5m

I will implement it when there's no more feedback for it.

**Comment by josojo** [comment]
I don't have access to it. Can you please provide it @gabriel?

My account is:
[image: image.png]
*Alexander Herrmann*
Mechanism Designer at Gnosis <https://twitter.com/gnosisPM>
<https://www.linkedin.com/company/gnosis-limited/>
<https://forum.gnosis.io/>  <https://chat.gnosis.io/>
------------------------------
<https://gnosis.io/>
*Gnosis Service GmbHwww.gnosis.io <https://www.gnosis.io/>*
Amtsgericht Charlottenburg | HRB 188071 B
Geschäftsführer: Dr. Friederike Ernst, Stefan George & Martin Köppelmann

**Comment by cmagan** [comment]
I propose to add also the total amount of auctioning tokens (from the token SC) and the % of token being auctioned from the total amount of tokens (allocation to the auction.
I think it'd be super useful info for users
@gabitoesmiapodo @josojo
