### ISSUE TITLE
WalletConnect: user appears to be disconnected after page reload

### ISSUE THREAD

**Issue by elena-zh** [gnosis/ido-ux#182]
1. Connect a wallet using WalletConnect
2. Reload the page

**AR**: user is disconnected
https://drive.google.com/file/d/1tZ1lHwaCQkNtjx4oCaRNErSjUUifVCRT/view

It causes the issue that an auction's details are not shown to a user
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/add79c01-d140-4365-a997-d0c3f8aad304)
and a user cannot place/cancel/claim orders: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/25fbc64e-d3b0-4ff6-8124-bd9deb2baf4f)

**ER**: user is connected.

**Comment by josojo** [comment]
Sorry, I can't really hellp. I know basically nothing about wallet connect
