### ISSUE TITLE
Incorrect validation messages when enter too long values into the price field

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#231]
If a user puts in a price as long as 4.000000000005, then the error message is wrong.
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9d98c50f-9dbf-4e9d-996c-51355c55cf08)

Sometimes, the same validatiton message may appear when amount corresponds to the condition (I mean, when amount>required one)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/cebf5cf0-b0b9-42c9-9038-d5eabad05384)

**Comment by elena-zh** [comment]
Fixed in #691
