### ISSUE TITLE
IPFS deployment: connection not working

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#292]
Steps to reproduce:
1. 
connect to mainnet with metamask.
2.
visit: https://bafybeicbhqrcixtztqlwtnxdnb2mymdwdda64q44x6f2zvqkznxmsavjje.ipfs.infura-ipfs.io/#/auction?auctionId=58&chainId=4#topAnchor
3.
switch metamask to rinkeby. 

and you will see:
![image.png](https://images.zenhubusercontent.com/5ddee9ea1d3e1600010ad960/62889214-1fce-41bd-b87f-b856aa89a81b)

But it should show the connect button instead of the warning. The connect button in the placeOrder field is correct and there it works correctly

**Comment by elena-zh** [comment]
HI @josojo , 
I have verified the issue and switched networks for different auctions in different networks. 
Seems to be working fine except one known issue #303 and a new one #391. 
I think, we can close this issue. 
Thanks

**Comment by mariano-aguero** [comment]
I will close this one, feel free to reopen it if the error is found again
