### ISSUE TITLE
Console Errors 403 on any network 

### ISSUE THREAD

**Issue by cmalfesi** [gnosis/ido-ux#298]
**Bug**: Show some console errors 403. It seems to try to load Rinkeby links while it is connected to the xDai network.
**Tested link**: https://ido-ux.dev.gnosisdev.com/#/auction?auctionId=1&chainId=100#topAnchor
Even, the problem happens connected to any network, connected to Rinkeby as well.
And continue making recurring calls to the same rinkeby point.

**Screeenshot**:
![image.png](https://images.zenhubusercontent.com/5e664bce015a7a82381ccd09/5fd7dbb9-c655-4c7d-a90e-c143a8ad4232)

![image.png](https://images.zenhubusercontent.com/5e664bce015a7a82381ccd09/3160b861-3dce-4b2d-8428-4acc29650599)

**Comment by elena-zh** [comment]
Should be fixed in #411

**Comment by elena-zh** [comment]
I'm closing this task as it is fixed in #411. 
However, each time when we reload the page, 4 unnecessary API calls appear; A separate issue for this case is created #417
