### ISSUE TITLE
Create a Dune Analytics list for orders 

### ISSUE THREAD

**Issue by Rafanator** [gnosis/ido-ux#312]
**Create a Dune Analytics list that shows all orders** 

The first iteration should have the following columns: 

| Price | Amount | Sum | My Size % 

- Price -> determines the price level of the bids in one row
- Amount -> Shows the amount that is being bid at that given row 
- Sum -> Shows the cumulative amount at that bid price, adding the amount of all higher bids form previous rows
- My Size % (maybe not possible for Dune Analytics) -> Shows the % of the `Amount` that the bid of the user has

**Possible button location**

Marked with the red rectangle: 
<img width="1228" alt="Screenshot 2021-03-25 at 15 11 20" src="https://user-images.githubusercontent.com/26544214/112486911-99c1ad00-8d7c-11eb-9c5f-cff85548cef7.png">

**References to orderbook lists**

A few images for inspiration. 

Binance: 
<img width="269" alt="Screenshot 2021-03-25 at 14 55 33" src="https://user-images.githubusercontent.com/26544214/112487068-bc53c600-8d7c-11eb-9c95-e345952e62bf.png">

dYdX:
<img width="291" alt="Screenshot 2021-03-25 at 15 14 37" src="https://user-images.githubusercontent.com/26544214/112487240-db525800-8d7c-11eb-878f-62e4c86742dc.png">

@cmagan Let me know if you think this would be enough.

**Comment by cmagan** [comment]
initial thought for layout including both chart and orderbook
https://files.slack.com/files-pri/T58NW6E06-F01TT6ANLF4/screen_shot_2021-04-09_at_11.46.58.png

**Comment by cmagan** [comment]
actually will create new issue for that

**Comment by Rafanator** [comment]
I don't like it in the same page, to crowded, would strongly prefer to have it as a toggle. 

@gabitoesmiapodo What do you think?

**Comment by gabitoesmiapodo** [comment]
> I don't like it in the same page, too crowded, would strongly prefer to have it as a toggle.
> 
> @gabitoesmiapodo What do you think?

I'm inclined to think that it will be too crowded, yeah. But it will depend on how many columns there are in the table, among other things. It may look OK with 4 columns, but if we add more later (and that's what usually happens...) we will run into trouble.

The form could be narrower, though, we don't need it to be too wide.

Anyways: what's the most important data the users need to have available all the time to take decisions? Do they need to compare data from the chart and the table? Do they need to compare this data against the data above (Auction Details)?

If that's the case, that's what should be available for the users all the time, and maybe we need to put the form on a toggle, or use a different layout.

We could even do something like:

1st row: Auction Details (we will probably add more info in https://github.com/gnosis/ido-ux/issues/152)
2nd row: Place Order (form) / Your Orders (table).
3rd row: Chart / Dune Table.

**Comment by josojo** [comment]
One example; 
https://duneanalytics.com/gnosis.protocol/Gnosis-Auction-Boson-Sale?DECIMALS_DIFF=12
