### ISSUE TITLE
App connects to MM even If the user is connected to WalletConnect

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/ido-ux#323]
> However, there the case: I'm returned to the Metamask wallet connection each time when I reload a page/navigate to another page even if I'm currently connected through the WalletConnect option.
 
> It does not seem to me a correct behavior. See the video https://drive.google.com/file/d/1D8YK_iCZAlnP3MMTcNbUh1954uWtyaOo/view

See https://github.com/gnosis/ido-ux/issues/164#issuecomment-802611964

**Comment by elena-zh** [comment]
fixed in #447
