### ISSUE TITLE
Auction's page is not auto-reloaded when the auction ends

### ISSUE THREAD

**Issue by elena-zh** [gnosis/ido-ux#330]
An auction's page is not auto-reloaded when the auction ends. 

![end time.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f7227aa1-f377-4f2a-b237-ba1f0ef3985f)

So the timer starts to show --:--:-- at the auction end time. 
A user can try to place an order for this auction and etc. https://rinkeby.etherscan.io/tx/0x1be06e74dce2c4aeca91e036c9df4528ec867c986703557f270fb19a1cd0c7cc

**Expected**: reload an auction's page when it ends

**Comment by gabitoesmiapodo** [comment]
Duplicate of #541
