### ISSUE TITLE
Already claimed message, although on a different network

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#339]
1. connect to mainnet:
2. go to finished rrinkeby auction:
https://ido-ux.dev.gnosisdev.com/#/auction?auctionId=80&chainId=4#topAnchor
3. observe the message: "already claimed"

![image](https://user-images.githubusercontent.com/7348154/112719861-7ec97700-8efb-11eb-802e-dc32a5931b8a.png)

Expected: Error message should notify the user that they arre on the wrong network

**Comment by gabitoesmiapodo** [comment]
It seems this was already fixed (or the issue is not the same).

I either get an "You had no participation on this auction." or "Price not yet supplied to auction." message. And instructions to connect to the right network are at the top.

@elena-zh could you have a look?

**Comment by elena-zh** [comment]
The issue is no longer reproducible.
