### ISSUE TITLE
Update auction info after order placement or cancellation

### ISSUE THREAD

**Issue by elena-zh** [gnosis/ido-ux#344]
When I place an order or cancel an order, I do not see an updated info on the auction details page. E.g. current price, chart, sometimes even details section are not updated and show the previous info until I manually reload the page. 
https://drive.google.com/file/d/1ohO3jhS47Xt1Ouu7WKSVZZVngbTdBkX-/view

It would be great to auto-update the page after receiving a 'successful' order placement/cancellation transaction response.

**Comment by josojo** [comment]
@henrypalacios 
for tthe orderbookchart, we already update the clearing price - the white line. You can just use this logic to calculate the new clearing price and display itt.

**Comment by henrypalacios** [comment]
@josojo I would like to know where the `current price` that is on the chart, I have hunch it is from [here](https://github.com/gnosis/ido-ux/blob/d712b0859991935906105f4b77e9a14df80bd37a/src/components/auction/OrderbookWidget/index.tsx#L332). But I still can't trace the output of the `currentPrice` value in  `proccessOrderbookData` function.

**Comment by elena-zh** [comment]
Hey @henrypalacios , 
I'm not sure if you have taken into account these cases, that is why I would like to mention them here. 
We have additional details section in an auction details page that shows 'Minimum Funding' and 'Estimated Tokens Sold', and it would be nice to recalculate these numbers as well when a user places/cancels orders.
![image](https://user-images.githubusercontent.com/70885163/121196097-dc256100-c878-11eb-937c-87e05247d1a7.png)

Could you please check it?
Thanks

**Comment by cmagan** [comment]
I'm not sure what input you need from me on this issue...
I think it'd be very useful to update the "current price", "minimum funding" and "estimated tokens sold"
The thing is, we should update them only once the order transaction has been included in a block

**Comment by josojo** [comment]
>The thing is, we should update them only once the order transaction has been included in a block

why do you think we should do it that way? isn't is clearer to the user, if there is only on coherent price shown in the whole app? In the past, people said that it's confusing that we show a different current price in the graph compared to the auction details.

I am quite unsure now...

**Comment by cmagan** [comment]
Yeah we should def update both at the same time!
I was just saying that it should be updated after the tx is confirmed and not just after submitted...

**Comment by josojo** [comment]
>I was just saying that it should be updated after the tx is confirmed and not just after submitted...

but right now, it is updated just on order placement indication, since the new order is getting into the graph

**Comment by cmagan** [comment]
I think it's two different features.
1. when a user considers amount and price, they can see his order and its impact in the chart using an orange indication
2. AFTER an order is confirmed to be included, "current price" should be updated all over the app

would you agree?
