### ISSUE TITLE
showing site, if only 1 endpoint is up

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#357]
If there is only one endpoint running: In this example only xdai is down, we should should still show the page properly, without xdai info
![image.png](https://images.zenhubusercontent.com/5ddee9ea1d3e1600010ad960/9bafcc5a-3b30-4abd-bc77-7e0301486b12)

**Comment by jarcodallo** [comment]
It was fixed on #367. I tested locally and works fine.

![image](https://user-images.githubusercontent.com/3802516/113132801-4ffe1a00-91f5-11eb-99f2-f8911ea7dec1.png)

**Comment by josojo** [comment]
I was hoping that still the auctions of the api's, which are working, are shown.
But this is not yet the case:
https://ido-ux.dev.gnosisdev.com/#/auction?auctionId=3&chainId=100#topAnchor
