### ISSUE TITLE
Amount to claim number is changing when switch between Rinkeby/ Mainnet/xDAI networks

### ISSUE THREAD

**Issue by elena-zh** [gnosis/ido-ux#391]
I opened an ended auction for the Mainnet when I was connected to Rinkeby (I had not placed orders for that auction)
Then I switched to Mainnet and back to Rinkeby

**AR**: amounts to claim were changing on switching networks
https://drive.google.com/file/d/116eAQj4IgkWp6lKGq_hz1GwVrF9lXYxX/view

when open details in xDAI: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2aa14db3-d23d-4121-a940-69f1224d12c5)

**ER**: amounts remain to be the same

**Comment by elena-zh** [comment]
I have retested the issue. 
Today prices remain to be the same. 
However, Price is blinking and 2 decimals appear) when auction details are reloaded. 
https://drive.google.com/file/d/1S4quAq4FM5xEWgpr-kb0S5Ubv1yOz_l9/view
This issue might be fixed in #347, so I will close the current task.

**Comment by elena-zh** [comment]
The issue appeared to be reproducible again
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/b1579337-1d9a-43ae-98c2-d65843d70e76)
Re-opened.

**Comment by josojo** [comment]
This was solved in one of my refactorings
