### ISSUE TITLE
Clearing price not updated in the featured auctions page

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#395]
On overview/ index page; current price is not updating
https://ido-ux.staging.gnosisdev.com/#/overview#topAnchor

Current clearing price 1.21, displayed current price

![image.png](https://images.zenhubusercontent.com/5ddee9ea1d3e1600010ad960/1762743b-e33e-446b-9607-2297302b277a)

ER: Should show the clearing price of 1.21

**Comment by elena-zh** [comment]
Dev env-t: auction?auctionId=15&chainId=4#topAnchor
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9b037b54-0385-4ae5-ac8a-12a28f2a0c86)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/bed37abc-2873-4688-a56b-6779e1d182d9)
