### ISSUE TITLE
Featured auctions widgets are moving along with timers

### ISSUE THREAD

**Issue by elena-zh** [gnosis/ido-ux#416]
Featured auctions widgets are moving along with timers: see the video
https://drive.google.com/file/d/1yHuzeFBaTe9DCdYSwQsLMGTWE0SiCNgd/view

**Expected**: widgets are fixed

**Comment by gabitoesmiapodo** [comment]
@elena-zh 

This was fixed on https://github.com/gnosis/ido-ux/pull/420/commits/8f5abc9c5c53369e0bdcd6f551e2c4a6b53b1c3b

You should be able to test it when https://ido-ux.dev.gnosisdev.com is updated.
