### ISSUE TITLE
UI for tablets

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#419]
ON my tablet, the UI starting page looks like that:
![image.png](https://images.zenhubusercontent.com/5ddee9ea1d3e1600010ad960/9c922578-f804-433d-a059-3c40c9a74248)

Could we please try to display the 'time until auction end' somehow nicer? Maybe it is the easiest solution to display only 2 featured auctions or 1 per row.

**Comment by gabitoesmiapodo** [comment]
Sure, I'll have a look.
