### ISSUE TITLE
Prod:  'Error: REACT_APP_ADDITIONAL_SERVICES_API_URL must be a defined environment variable for network 4' when open ended auction

### ISSUE THREAD

**Issue by elena-zh** [gnosis/ido-ux#440]
1. go to https://gnosis-auction.eth.link/
2. connected to the Rinkeby network
3. open any ended auction

**AR**: a lot of  errors 'Error: REACT_APP_ADDITIONAL_SERVICES_API_URL must be a defined environment variable for network 4' in the console. auction details are not loaded

**ER**: no errors in the console, user is able to see claim section as a not connected user.

**Comment by josojo** [comment]
It's because we don't provide the rinkeby version of REACT_APP_ADDITIONAL_SERVICES_API_URL on produciton. I will look into it

**Comment by elena-zh** [comment]
If we remove Rinkeby support from production, we need to update this tooltip as well then
![image](https://user-images.githubusercontent.com/70885163/113699731-a0d2ae80-96de-11eb-987e-ff0de8cea6ee.png)
