### ISSUE TITLE
walletconnect not working without metamaks

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#467]
One user reports:

Anyone else having problems to use wallet connect?
There is no response when i click in wallet connect

and another one is helping out:

I had same issue. Try using the link above it to instal the metamask plug in on your browser (even if you don’t have a metamask account or any intention of using it). The walletconnect button started working after I did this.

**Comment by elena-zh** [comment]
The issue seems to be fixed in #470 pr. 
However, in order not confuse users and do not force them to install Metamask, I created #478 bug to fix.
