### ISSUE TITLE
'Install Metamask' button is enabled when 'Terms' box is unchecked

### ISSUE THREAD

**Issue by elena-zh** [gnosis/ido-ux#478]
1. Disable metamask in browser
2. call the connection modal 

**AR**: 'Install Metamask' button is enabled when 'Terms' box is unchecked
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d630f32f-5628-4d76-a664-07710544edfc)

**ER**: 'Install Metamask' button should be disabled when 'Terms' box is unchecked

**Comment by gabitoesmiapodo** [comment]
This is not a bug, you should be able to click on it to install Metamask. No wallet interaction will exist when the user clicks on it.

Once MM is installed (or enabled) it should change to the actual "Connect to Metamask" button and it should be disabled until the user accepts the terms.

**Comment by elena-zh** [comment]
Yes, I understand that it is not a bug.
However, users are confused when the app forces them to install metamask even if they do not intend to (case 2 in #467). 
That is why I created this issue.

**Comment by gabitoesmiapodo** [comment]
Yeah, but it's still not a bug. 

It's the intended behavior, pretty common in dApps (maybe not the nicest, though).

For example: disable MM and check out this app https://app.uniswap.org/#/swap (it's actually the same base code we used for GA).

**Comment by elena-zh** [comment]
Yes, understand. 
I have changed the issue label to 'enhancement'. 
Thanks!
