### ISSUE TITLE
Create a native user flow for wrapping and unwrapping 

### ISSUE THREAD

**Issue by cmagan** [gnosis/ido-ux#499]
As we implement the smooth user flow for submitting bids with native tokens (ETH/xDAI), we need to take care of the user flow for claiming and unwrapping (which for now cannot be bundled).
I was thinking about two solutions, we can also implement both:

1. In the claiming interface add a small section / button just for unwrapping. This will need to be active only if the user has tokens he needs to unwrap.

2. Have a dedicated pare for wrap+unwrap for all kind of situations.

@gabitoesmiapodo @Rafanator @josojo WDYT?

**Comment by josojo** [comment]
Actually, I think it's sufficient to link users to this:
https://app.honeyswap.org/#/swap?outputCurrency=0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d

via a button: 
```
Unwrap WXDAI on HoneySwap
```
if the user has auction proceeds in xdai
