### ISSUE TITLE
[Wallet connect]

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#505]
When one clicks the button disconnect, the wallet connect session is not close, though it should be.

**Comment by elena-zh** [comment]
Hi @josojo , 
I'm not able to reproduce the issue in Dev environment (in prod only). So it is might be fixed in dev, hence we can close the issue. Or  it is still reproducible for you?

Thanks

**Comment by josojo** [comment]
Yes, @hpmaxi fixed this. All good
