### ISSUE TITLE
Suggest the user to add network to metamask switch automatically 

### ISSUE THREAD

**Issue by cmagan** [gnosis/ido-ux#513]
This applies at the moment for xDAI but later to any other network we'll add...
You can see an example here
https://chainlist.org/

I think this should be suggested every time the user is watching an auction while being connected with the wrong network

**Comment by cmagan** [comment]
example for switching networks automatically https://app.honeyswap.org/#/swap

**Comment by josojo** [comment]
Probably, I will only be able to implement it with limitations, see here:
https://stackoverflow.com/questions/66588495/switch-metamask-network-to-chain-1-ethereum-mainnet

But I will continue to investigate.

Metamasks implementation is here:
