### ISSUE TITLE
Orderbook list integration

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/ido-ux#527]
Implementation of orderbook list

**Comment by elena-zh** [comment]
Hi @ramirotw , @josojo , @cmagan 
Here are some questions: 
1. What is default sort order of lines displaying in the orderbook?
2. Could you please provide texts for tooltips: 
![image](https://user-images.githubusercontent.com/70885163/120623231-39c84080-c468-11eb-8aed-1585767426ed.png)

3. Should we have sorting asc-desc for the table columns?

Thanks

**Comment by josojo** [comment]
All these following answers are tentative answers and we should double check that they are making sense. Please voice your opinion

1. It should be the price for sure, starting with the highest price
2. Just a suggestion:
Price: 
Price range of limit orders for a given granularity
 Amount: 
 Sellamount of all orders  in the rows particular price range
  Sum:
 if(inverteredPrices())
 Culumittive sum of sell amounts of all orders with a limit price higher than the price mentioned in the price column
 else
 Culumittive sum of sell amounts of all orders with a limit price lower than the price mentioned in the price column
 
MySize:
Percentage of your sellamount in the overall sellamount of this column.

3. See 1)

4. Just an empty table

5. Yes! It contains the same information as the chart and hence all the information is available anyways.

6. The value closes to: (MaxPrice-MinPrice)/10, where MaxPrice and MinPrice are the prices for ending the display of the green and red line in the orderbook-chart. --> If other reasonable solutions are easier to implement, I am happy to change this requirement

**Comment by cmagan** [comment]
Not sure I like the name granularity. The literal meaning is good but I think not many people will be familiar with it
On binance they don't have a name but just the decimal accuracy:
![image](https://user-images.githubusercontent.com/6940448/121861397-73b80300-cd02-11eb-8c3e-dc1f615839fc.png)

On Karken they have special setting 
![image](https://user-images.githubusercontent.com/6940448/121861636-a6fa9200-cd02-11eb-89eb-ba7492557a1c.png)


I'm also unsure about the way orderbook should work in a "buyback" scenario. In this case people are not placing bids but "asks" (and the auctioneer placed a big bid)
So maybe it's better in this case to show lowest price in the top?
