### ISSUE TITLE
Price are displayed weirdly

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#532]
Can we please get a fix for the prices? 
If the tokenname is longer, usually prices are displayed very strangely.

![image.png](https://images.zenhubusercontent.com/5ddee9ea1d3e1600010ad960/53054876-1099-43c4-ba10-3ea5285b0d6d)

**Comment by josojo** [comment]
33.33/newline 3 is really strange.

I see two solutions:
- write it in a smaller letters. 
- write it above SNAFU per

**Comment by gabitoesmiapodo** [comment]
This is gonna be fixed when the new design is implemented.

**Comment by josojo** [comment]
How long will it take? Because the customers are currently complaining about it...

**Comment by gabitoesmiapodo** [comment]
> How long will it take? Because the customers are currently complaining about it...

It's going to take a while, there's still plenty to do.

We could implement a hotfix for this, though, and discard it later.

**Comment by Agilulfo1820** [comment]
Hi, I'm from SNAFU team, and this bug is causing us a bit of problems since people is thinking that's the price of our token, and since we made the auction last only 3 days I guess we are just fucked .-.

Also numbers on offers already made are changing.
