### ISSUE TITLE
Auction should automatically get into the new state

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#541]
Once an auction is over, it just pauses in such a screen:
![image.png](https://images.zenhubusercontent.com/5ddee9ea1d3e1600010ad960/4bda0941-eb69-41c7-a54c-d80f2aadb355)

but it should automatically flip into this one:
![image.png](https://images.zenhubusercontent.com/5ddee9ea1d3e1600010ad960/a12e8962-072d-4353-9ad0-73b0d7425b97)

**Comment by elena-zh** [comment]
Hi @josojo , @henrypalacios , 
I'm re-opening the issue as it has become reproducible again 
![image](https://user-images.githubusercontent.com/70885163/124448962-a5653c80-dd8b-11eb-90d2-7ca5153bc4ce.png)

**Comment by elena-zh** [comment]
It happened only once.. Some kind of a glitch, I believe. I will close the issue for now...
