### ISSUE TITLE
Auction pending settlement state

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#542]
Currently, the user is just getting a tiny warning:
```
auctionprice not yet supplied!
```

and most users don't understand it.

We should have a proper warning that is more informative.

1. Suggestion:
Write into the orange button in bold:
``` 
Waiting for on-chain price calculation
```
2. Suggestion:
Define a new state and show it in the orange circle

3. Suggestion:
Just replace the current message with a better one.

What do you guys think?

**Comment by josojo** [comment]
Let's go with suggestion 1

**Comment by maria-vslvn** [comment]
@bh2smith @cmalfesi  could you please give me more details about the issue, or steps to reproduce the message mentioned above

**Comment by bh2smith** [comment]
@maria-vslvn 

> @bh2smith @cmalfesi  could you please give me more details about the issue, or steps to reproduce the message mentioned above

When an auction ends, someone (anyone) must send a transaction onchain to essentially perform the final price calculation (the auction's closing price - note what is shown in the interface is merely an off chain calculation so it can be displayed in the interface). Before this final closing transaction is submitted onchain successfully, users can't claim their tokens. At the moment people are confused by the current message being displayed and this issue aims on to fix that by providing a more descriptive message to the user.

**Comment by maria-vslvn** [comment]
@josojo do you expect this kind of result
?![1.png](https://images.zenhubusercontent.com/60a26634acdb8bf86a8e04f1/0081b07c-8de1-489a-b0c4-5516d8954d57)

**Comment by bh2smith** [comment]
> @josojo @cmalfesi  do you expect this kind of result?![1.png](https://images.zenhubusercontent.com/60a26634acdb8bf86a8e04f1/530351d0-f167-4058-afc9-f22defc3de44)

That very much depends on what wallet you are connected with. 

I would expect that from an account that didn't participate in the auction and so doesn't have a balance of either token involved on the auction contract.

**Comment by josojo** [comment]
> @josojo @cmalfesi do you expect this kind of result?![1.png](https://camo.githubusercontent.com/84a91ca725f050db17428951a200f2ae290fba464f17e00087ba5bd09622f1c7/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630613236363334616364623862663836613865303466312f35333033353164302d663136372d343035382d616663392d663232646566633364653434)

Close :) 
this issue is about auctions that are finished , but there was not yet any onchain price calculation done. Eg. this auction:
https://ido-ux.dev.gnosisdev.com/#/auction?auctionId=117&chainId=4#topAnchor

And then I was suggesting to write it this error into the  current "claim/button".
