### ISSUE TITLE
[UI] Add dollar value estimation for the bidding interface

### ISSUE THREAD

**Issue by cmagan** [gnosis/ido-ux#549]
When placing a bid in an IDO that raises in a token other than a stablecoin, the user has a hard time valuing his bid.
A dollar estimation can help
![image.png](https://images.zenhubusercontent.com/60227f03bd43d8095c1185d0/478e591f-6d76-45e5-b7fb-1906c679e764) 
![image.png](https://images.zenhubusercontent.com/60227f03bd43d8095c1185d0/a21537ca-d553-4418-bbb6-3559ff734ff9)

**Comment by josojo** [comment]
From which api should we get the prices? 

Maybe the uniswap prices and we get it via ethereum rpc?

**Comment by cmagan** [comment]
Yeah good question.
I'd be interested to know how uniswap or cowswap implemented it.
One option will be to use a uniswap swap token->USDC
Another option is just to use coingecko

**Comment by josojo** [comment]
Yes, let's use the uniswap price and also the implementation from the uniswap page

**Comment by cmagan** [comment]
Yes, I think it is good but maybe we need a bit smaller font or something to make sure people understand it is just added info which is not critical for placing the bid...
![image](https://user-images.githubusercontent.com/6940448/121863482-92b79480-cd04-11eb-95f1-dba6a0e63c95.png)

**Comment by alongoni** [comment]
Hey @cmagan I made some litle adjustement on the text size and opacity. What do you think?
1) Text size: 14px
![23b- GnosisAuction - Auction v2-1](https://user-images.githubusercontent.com/622217/122111201-d4743800-cdf5-11eb-878e-4c9198e4a5e3.png)

2) Text size: 12px + opacity 
![23b- GnosisAuction - Auction v2](https://user-images.githubusercontent.com/622217/122111193-d3430b00-cdf5-11eb-8204-ce192b92a347.png)

**Comment by cmagan** [comment]
Cool!
I think for me 14px looks better but I guess it depends on resolution and size of screen...
You can decide on the exact details
