### ISSUE TITLE
[UI] Showing highest volume auctions

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#553]
In order to give new users a quick overview of how great auctions could look like, I think we should have a new section at the bottom of the landing page, that shows the highest volume auctions;

It could look like that:
https://docs.google.com/presentation/d/1RxkQqPepdSgr58wPXLscWd5BBmxen6uOs7AVwyOktcM/edit?usp=sharing

**Comment by josojo** [comment]
@cmagan What do you think about this requirement? Should it have a high prio?

**Comment by cmagan** [comment]
I need to review the prio vs other issues...

I can tell that one potential IDO was asking about previous high volume IDOs.
It really is an 'indication of success' and if such, we should present them clearly

**Comment by alongoni** [comment]
hey @josojo @cmagan. I did this first draft for this issue. The main idea is to show the auction evolution by presenting a starting point and the final state (raised amount).  I'm not sure if I'm using the correct wording or terms.
Anyway, I am sending you the [Figma file for feedback](https://www.figma.com/proto/Y7MLpZujRAOFPVkplvA7kV/Gnosis-Auction?node-id=10%3A32&viewport=175%2C79%2C0.08190692961215973&scaling=scale-down-width&page-id=0%3A1%3Ffuid%3D789860674698606135).

Screenshot:
![02- GnosisAuction - Landing v2](https://user-images.githubusercontent.com/622217/120381808-4bd7a100-c2f9-11eb-8429-b01798370dfe.png)

**Comment by alongoni** [comment]
Hi @josojo and @cmagan I've upgrade the design and fix some small details. You can [see it on Figma](https://www.figma.com/proto/Y7MLpZujRAOFPVkplvA7kV/Gnosis-Auction?node-id=53%3A0&viewport=175%2C-507%2C0.13933944702148438&scaling=min-zoom&page-id=0%3A1%3Ffuid%3D789860674698606135)

We can also add a column with the amounts expressed in U$D (or other fiat currency).
![image](https://user-images.githubusercontent.com/622217/120707427-af480700-c490-11eb-8d73-bcf90cb0e718.png)

cc @ramirotw

**Comment by elena-zh** [comment]
Could we change 'Ended In' column name to 'End date'?

**Comment by josojo** [comment]
Where can I find the newest figma file with the Volume [USD] column? Somehow I can still not navigate properly in figma.

In case the volume column was forgotten, can we please switch the Participant column with the Volume column?
Otherwise, it looks good! I also implemented the usd_amount estimation already

**Comment by cmalfesi** [comment]
@maria-vslvn Please implement it on UI

**Comment by ramirotw** [comment]
@josojo a few questions to have more context:

1. how the table should be sorted? by usd amount, volume or end date?
2. what was your suggestion for usd amount in auctions with not stable bidding tokens?

**Comment by cmagan** [comment]
I think we agreed to store a table of prices for the bidding token at the time that each auction closes.
If the bidding token is stable the price will probably be ~1.
Then we can produce a table with the $ amount raised by each auction (which will be accurate to the time when the auction has ended and not updated to current prices)

I think the "Highest Volume Auctions" table should be sorted by $ amount raised by default

**Comment by josojo** [comment]
>how the table should be sorted? by usd amount, volume or end date?

they are already presorted in the backend by the USD amount

>what was your suggestion for usd amount in auctions with not stable bidding tokens?
Currently, we will just leave them out. I will update the backend later to also incorporate them. I think it has no high priority right now. No work is needed in for FE for that.

**Comment by elena-zh** [comment]
> I think we agreed to store a table of prices for the bidding token at the time that each auction closes.

One question, please. Since ongoing auctions can also be displayed in the table, how the bidding token amount in USD be calculated for it?

**Comment by cmagan** [comment]
This is a good point.
For ongoing auctions we have the "Featured Auctions" section.
So maybe on the table we should present only auctions that have ended?
