### ISSUE TITLE
Has pending claim

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#560]
Currently, we are only looking whether a user has a pending approval, but we should do the same thing for claim txs. 
Some users don't understand ethereum logic too well and hence started the claiming very often. E.g this user.

https://etherscan.io/tx/0xafd215353d3f4d1111e653a7ee99398d261dc90c98a7eb5fc7d86d339d30c95c

Expected behavior:

- user start claim processes
- show that the tx in progress, if they started the tx ( similar as approval): (Button should be disabled and should show "claiming", exactly as as "approving- button"

**Comment by henrypalacios** [comment]
Hi @josojo, I have not been to reproduce this.

Let me tell you that I tried.

1. I have created a new Auction and after it is finished, I press the "claim" button then  I could not make a new claim.
![Screenshot from 2021-05-13 15-20-14](https://user-images.githubusercontent.com/4270166/118188791-51874880-b417-11eb-9d7c-573fbd06cefb.png)


2. I though it might only happen at a private auction so I tried to create one but I couldn't get past "**Private Auction**" interface, even though executing this **command** tells me its is done.
```bash 
yarn hardhat generateSignatures --auction-id "87" --file-with-address "./Address.no-commit.txt" --network rinkeby --post-to-api
```

📝 `Address.no-commit.txt` had this:
`0xb6BAd41ae76A11D10f7b0E664C5007b908bC77C9,0x1F8D2668BAaB2B324f61fCf34730BE8e79e8eCCF`

**Comment by josojo** [comment]
It's about the situation, where the pending claim tx is in flight. That means the tx was already approved in the wallet, but not yet mined. It's hard to reproduce on test networks, as here, tx are nearly always mined instandely. But on mainnet, mining takes a long time, especially, if a user chooses low gas prices.
