### ISSUE TITLE
Wallet connect deep link

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#562]
On mobile, uniswap is offering this deep connection:
![image.png](https://images.zenhubusercontent.com/5ddee9ea1d3e1600010ad960/3bad2147-d65d-43f9-bb86-f1b45f6cffcd)

We should copy the uniswap workflow to our site to allow this feature

**Comment by cmalfesi** [comment]
@alongoni please, take it and advice a new UI design

**Comment by josojo** [comment]
I think. we should use the `@walletconnect/qrcode-modal` package, if we get it running. I don't see an advantage of rebuilding this logic. 

Our own modal logic is just a few lines of code, if I remember correctly.
