### ISSUE TITLE
Tooltips to be fixed

### ISSUE THREAD

**Issue by cmalfesi** [gnosis/ido-ux#576]
![image.png](https://images.zenhubusercontent.com/5e664bce015a7a82381ccd09/c4a8d333-1868-491f-af89-cbf28a8ca898)

![image.png](https://images.zenhubusercontent.com/5e664bce015a7a82381ccd09/55403cce-f21d-4aa6-a044-75d7abaebc09)

**Comment by ramirotw** [comment]
z-index was fixed in https://github.com/gnosis/ido-ux/pull/570

**Comment by elena-zh** [comment]
another issue is created for the 1st image in this issue #652
