### ISSUE TITLE
[list of auctions] wrong tooltip view

### ISSUE THREAD

**Issue by tatyanakurinskaya** [gnosis/ido-ux#579]
1. open app
2. follow Auctions from header

Result: ![Screen Shot 2021-05-19 at 18.16.36.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/7e5b14a2-9a7e-43b3-8e50-13f07371f40d)

**Comment by ramirotw** [comment]
This was fixed in https://github.com/gnosis/ido-ux/pull/570
