### ISSUE TITLE
[auction details] place order button becomes enabled if amount=0

### ISSUE THREAD

**Issue by tatyanakurinskaya** [gnosis/ido-ux#580]
1. open app
2. follow Auctions from menu
3. open auction 
4. click MAX or enter 0
5. fill in the price with 0 as well

**Result:** Place order button becomes available ![image.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/b43751cf-6e9a-4af9-83e7-44f8ed4c893d)
![image.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/5839d45d-a4a6-4279-afd4-0394e5092165) 
**Exp.result:**  Place order button is disabled. 
Also, it would be nice to show validation messages for the fields when they are empty/filled in with 0 amounts

**Comment by elena-zh** [comment]
Hi @henrypalacios , changes for ordinary price LGTM!
However, 
1. when a price is inverted, it is a bit confusing to see than amount should be less than <min price> when we enter 0. 
![image](https://user-images.githubusercontent.com/70885163/122541243-18ec1780-d032-11eb-8034-159d8308c78f.png)
It would be nice to save the logic for 'inverted prices' 
 - 0: 'Price must be higher than 0'
 - and then, if an amount is greater than min price, show 'Price must be lower than <min price>'

2. Then, the next case is related to an auction state when order cancellation is not allowed. Min price is used for validation
![image](https://user-images.githubusercontent.com/70885163/122543496-84cf7f80-d034-11eb-814f-451edc75e918.png)


User should see message 'price should be higher than <current price>'  in such case

![image](https://user-images.githubusercontent.com/70885163/122542918-e6431e80-d033-11eb-973c-6e224de5eed9.png)
