### ISSUE TITLE
missing privacy policy and cookie policy

### ISSUE THREAD

**Issue by tatyanakurinskaya** [gnosis/ido-ux#597]
1. open terms&conditions https://ido-ux.dev.gnosisdev.com/#/terms-and-conditions
2. follow privacy policy and cookie policy links

Result: ![Screen Shot 2021-05-20 at 17.42.54.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/cfd9f6fe-94d9-479a-92eb-dbd6812d95f9)

![Screen Shot 2021-05-20 at 17.43.54.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/c284e78f-a8e2-4d8b-b956-ee6cae848199)

**Comment by josojo** [comment]
Let's wai for legal feedbakc

**Comment by elena-zh** [comment]
Hi @josojo , 
I'd rather keep this issue opened with a low priority label until we get a legal feedback in order not to create a lot of additional issues in case if policies pages are needed...
