### ISSUE TITLE
[connect a wallet modal] wrong header 

### ISSUE THREAD

**Issue by tatyanakurinskaya** [gnosis/ido-ux#599]
1. open app
2. click Connect a wallet

Result: 
![image](https://user-images.githubusercontent.com/70885163/121315103-b0ee5080-c910-11eb-9e16-938ff2c3fc0d.png)

Exp.result: Connect a wallet

**Comment by elena-zh** [comment]
@ramirotw , I do not see any changes in Dev environment. 
Is this issue deployed there?
