### ISSUE TITLE
[app] tooltip and placeholder do not correspond each other

### ISSUE THREAD

**Issue by tatyanakurinskaya** [gnosis/ido-ux#602]
1. open Gnosis Safe, follow APPS, open Gnosis Auction Starter
2. select Do you want to use whitelisting process for your auction?
Result: ![Screen Shot 2021-05-21 at 09.50.07.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/e156673e-8e36-41f9-bcb5-911dfa3c252a)

**Comment by elena-zh** [comment]
The issue is moved to ido-starter repository https://github.com/gnosis/ido-starter/issues/55
Closed.
