### ISSUE TITLE
[auction details] Signer Address and Allow List Contract are None all the time

### ISSUE THREAD

**Issue by tatyanakurinskaya** [gnosis/ido-ux#604]
1. open app
2. open some private auction
3. click more details
4. look at Signer Address and Allow List Contracts values

Result: ![Screen Shot 2021-05-21 at 10.51.31.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/ebd1759d-5c8e-4569-a409-97ae82144e3e)
 
It shows None value but on clicking icon near it opens new link in etherscan

**Comment by josojo** [comment]
I think this is not so important. It brings you to the 0 address, which is the actual value that is set. But you guys are right, that it might be confusing for the users


Hence, I changed the prio

**Comment by elena-zh** [comment]
Hey @josojo , 
but what about the private auction? None is also displayed there, however, at least signing address should be visible..

**Comment by josojo** [comment]
Okay, this is strange. Yes, definitively a bug. Thanks for pointing it out.
