### ISSUE TITLE
reconnect to xDai automatically, without clicking 'Connect to a wallet'

### ISSUE THREAD

**Issue by tatyanakurinskaya** [gnosis/ido-ux#611]
open app
click Connect to a wallet and connect to MetaMask, rinkeby network
switch to xDai network in Metamask

Result: app shows 'Connect to a wallet'
Exp.result: reconnect to xDai network automatically

to compare, if I am connected to Mainnet and switch to rinkeby, it does not require to click Connect to a wallet when select rinkeby in MetaMask

**Comment by elena-zh** [comment]
Duplicate of #303
Closed
