### ISSUE TITLE
[place order] wrong validation when set Max bidding price to 0

### ISSUE THREAD

**Issue by tatyanakurinskaya** [gnosis/ido-ux#616]
1. open app
2. open some active public auction
3. fill in the Amount field
4. Fill in the Max bidding price field with 0

**Actual Result:** validation message under the Amount field appears
![image.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/82662770-6ea4-47df-b205-25cba20bb9aa)

**Exp.result:**  validation under the Max bidding price field appears: 'Max bidding price must be bigger than <>'

**Comment by elena-zh** [comment]
Hey @josojo , 

The seems to be still reproducible: 
![image](https://user-images.githubusercontent.com/70885163/121360011-b5306300-c93c-11eb-93e7-58d0be2c839a.png)

Incorrect validation message appears under the Amount field when I enter 0 price or clear out the price field at all.

Could you please take a look into the issue once again?

Thanks
