### ISSUE TITLE
[chart] green line and tooltips show incorrect values

### ISSUE THREAD

**Issue by tatyanakurinskaya** [gnosis/ido-ux#620]
1. start some auction
2. open app
3. open this auction
4. place some orders 
![Screen Shot 2021-05-26 at 09 44 15](https://user-images.githubusercontent.com/863519/119614624-2b927880-be07-11eb-8347-fb1b388597d6.png)

Result: 
![Screen Shot 2021-05-26 at 09 46 22](https://user-images.githubusercontent.com/863519/119614757-57adf980-be07-11eb-85be-f838c8601bbd.png)
![Screen Shot 2021-05-26 at 09 48 08](https://user-images.githubusercontent.com/863519/119614968-8af08880-be07-11eb-906b-408cb6f1778a.png)
![Screen Shot 2021-05-26 at 09 47 27](https://user-images.githubusercontent.com/863519/119614983-8deb7900-be07-11eb-9cc9-a75306ffb2b7.png)

**Comment by ramirotw** [comment]
@josojo was this ticket moved to Review for anything in particular? Or should we move it to Sprint Backlog if its high priority

**Comment by josojo** [comment]
I have not moved it.

I also don't understand the ticket itself. What is the exact issue? That the price and amounts are rounded? The numbers look correct to me. But maybe I am blind

**Comment by elena-zh** [comment]
Chart values look good to me as well besides a known issue #376 .
I'm closing it
