### ISSUE TITLE
[auction details] no autorefresh page when auction ends and user stays on auction details page

### ISSUE THREAD

**Issue by tatyanakurinskaya** [gnosis/ido-ux#627]
1. open app
2. start an auction 
![Screen Shot 2021-05-27 at 22 46 07](https://user-images.githubusercontent.com/863519/119892093-6b11af80-bf42-11eb-8b74-503a1156d2e2.png)

3. place some orders
4. open auction details page and wait for the end

Result: ![Screen Shot 2021-05-27 at 23.17.18.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/51406f5a-5b52-4c51-a585-9f963cff89bb)

when refresh this page looks ![Screen Shot 2021-05-27 at 23.18.06.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/6197f1d2-0382-4cb2-9de5-80aa70fa6c2e)

+ check Your orders section

**Comment by elena-zh** [comment]
I'm closing the issue as it is no longer reproducible.
