### ISSUE TITLE
Font family missing

### ISSUE THREAD

**Issue by alongoni** [gnosis/ido-ux#628]
There are some text and buttons labels that have a generic (fallback) font. We should use Averta font-family across the dapp.

https://www.loom.com/share/ca8de96445be493cbeacd40ed2406b6b

- Connect Wallet link.
- Place Order button label.
- Inputs numbers (on Place Order section)
![image](https://user-images.githubusercontent.com/622217/120010469-91236800-bfb3-11eb-9efd-bfe623c35499.png)

**Comment by josojo** [comment]
Nice catch! It does not have a very high prio, but I like the catch!
