### ISSUE TITLE
add status icon to pop-up window after tx passes/fails

### ISSUE THREAD

**Issue by tatyanakurinskaya** [gnosis/ido-ux#632]
1. open app
2. open some active auction
3. place an order
4. cancel order

Result: ![Screen Shot 2021-05-31 at 10.44.56.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/71814172-e9e5-4016-b47f-244e2a54c8c1)
Exp.result: It would be good to add icons as it is done here: ![image.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/8a85f136-a215-4c6d-bdd6-8da830f9302b)

see all actions and use appropriate icon

**Comment by alongoni** [comment]
I've added two variants for notifications:
![image](https://user-images.githubusercontent.com/622217/124020711-032b0a80-d9c1-11eb-9938-6cf5ebb86fa4.png)

At the bottom of the notification's container there is a progress bar to represent the time left to auto close the notification. It's implemented but I suggest make it 3px height.
Maybe we have to review the wording for the error state.
https://www.figma.com/file/Y7MLpZujRAOFPVkplvA7kV/Gnosis-Auction?node-id=198%3A452

**Comment by josojo** [comment]
Yes, the variants for the notification are better than the status quo. Like it

WHich wording should we review? Just the cancellation messages? They are looking good

**Comment by alongoni** [comment]
![image](https://user-images.githubusercontent.com/622217/124286916-cfb5c080-db25-11eb-8c21-38ee2afea33a.png)
@josojo Thanks! Also added this variant with thinner icons. 
Regarding the messages I was trying to say that the screenshot have a simulated text.

**Comment by josojo** [comment]
I like the bolder icons more. :)
