### ISSUE TITLE
[safe-app] make loading in Build transaction button smaller + add space between loading and text

### ISSUE THREAD

**Issue by tatyanakurinskaya** [gnosis/ido-ux#633]
![Screen Shot 2021-05-31 at 14.35.04.png](https://images.zenhubusercontent.com/5d9d8c5f5fc4fd000158a431/5c3b484c-1f6f-489c-bf60-8bafd1143e49)

**Comment by elena-zh** [comment]
The issue is moved to 'ido-started' repo https://github.com/gnosis/ido-starter/issues/56
the current one is closed.
