### ISSUE TITLE
Support navigates to 'Invite Invalid' page

### ISSUE THREAD

**Issue by elena-zh** [gnosis/ido-ux#638]
related to #556
press on the 'Support' link in the footer

**AR**: Support navigates to 'Invite Invalid' page
https://discord.com/invite/dR5znXE4
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/fea061a4-9166-4bda-b15e-930882350121)

**ER**: Support navigates to https://discord.com/invite/M39dTHQ

**Comment by ramirotw** [comment]
@josojo @cmagan guys what's the correct link for Discord?

**Comment by elena-zh** [comment]
@ramirotw , https://discord.com/invite/M39dTHQ

**Comment by cmagan** [comment]
Just making sure this link is not expiring...
@avsavsavs can you help to check it?

**Comment by josojo** [comment]
Yes, it will not expire. I double checked it.

**Comment by avsavsavs** [comment]
Yes @elena-zh & @cmagan, that link is correct, and should not be invalidated. Although, if you prefer to have a better URL, you can also use https://chat.gnosis.io/, which redirects to that invite.

**Comment by elena-zh** [comment]
@josojo , @cmagan should I create a new task to change the link?

**Comment by josojo** [comment]
No, the user never sees it, hence it makes no difference for them
