### ISSUE TITLE
WalletConnect: the app is crashed when connect a wallet with another supported network on auction details

### ISSUE THREAD

**Issue by elena-zh** [gnosis/ido-ux#658]
1. Open any ongoing public auction details (as an example, in Rinkeby)
2. Connect a wallet in, as an example, Mainnet using WalletConnect

**AR**: the app is crashed. It is impossible to reconnect a wallet once again as it appears that the session is already established in the connected app. That is why I always get a crash when I try to connect a wallet again using walletconnect option
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c6650960-4955-4afe-8162-d213776d6167)
https://drive.google.com/file/d/1v3anF2Ppz9ait75Pi2JdGOhLQSu_aU9P/view

**ER**: the wallet is connected, message to switch a network is displayed

**Comment by ramirotw** [comment]
Related to #502, when the auction's network is incompatible with the wallet's network the app crashes. The app should display a network selector as suggested in #502.

**Comment by henrypalacios** [comment]
I found some issues that confirm what Ramiro says. For example [this one](https://github.com/WalletConnect/walletconnect-monorepo/issues/427)
