### ISSUE TITLE
[Order Book] Tooltips are truncated in the chart

### ISSUE THREAD

**Issue by alongoni** [gnosis/ido-ux#667]
Related to #570

There is a problem with the tooltips width or z-index position.
https://www.loom.com/share/ffb666930f0244dfbda84eff056c6bba

How to test:
As a user point the cursor on the legends. On legend's hover state the tooltips are partially displayed.
![image](https://user-images.githubusercontent.com/622217/121388925-447c4d00-c922-11eb-976b-f4aa498ea4a6.png)

Where to test:
https://pr570--idoux.review.gnosisdev.com/#/auction?auctionId=17

Possibles solutions:
- Set a max-width to the tooltips.
- Set a higher z-index value.

**Comment by elena-zh** [comment]
Fixed in #674
