### ISSUE TITLE
Better number display for vita auction

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#692]
Hey guys,

I just tested how the numbers are displayed in the vita auction in the graph. (its only a. test auction, but with the right numbers)

![image.png](https://images.zenhubusercontent.com/5ddee9ea1d3e1600010ad960/79871c52-a129-48aa-adac-8d7bb09d5c6f)

Can you please make sure that in the green box more digits are shown for the price, such that people can better see their bidding amounts? Thx

**Comment by elena-zh** [comment]
@josojo , do I understand correctly that 
 - price should contain up to 6 decimals
 - no changed needed for the Volume in the green box?

**Comment by josojo** [comment]
>price should contain up to 6 decimals

For this example, I think so yes. THe developer can just use: .toSignificant(2) and it will show the last 2 significant digits. I think this would provide the best user experience
