### ISSUE TITLE
Incorrect amount to claim tokens in case if Minimum Funding is not met

### ISSUE THREAD

**Issue by elena-zh** [gnosis/ido-ux#694]
1. Create an auction with a Minimum Funding amount
2. Place several orders with a total amount< Minimum Funding
3. Wait till the auction ends, settle it
4. Verify an amount to claim +run claim transaction

**AR**: sell tokens are displayed for claiming, however, a user gets buy tokens back as a Minimum Funding amount  is not  met
see the image
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ad5a746d-2e85-441e-81f1-7368a568c5c4)
https://rinkeby.etherscan.io/tx/0x0389b85270159fa37337efa69c347b3dbc67b9c9d500c014c4159207a1233f1d

**ER**: buy token amounts should be displayed for claiming

**Comment by cmagan** [comment]
For the vita DAO auction I'm pretty confident that the minimum funding will be met...
But yeah this is nasty bug that might cause confusion...
Agree this is high priority
