### ISSUE TITLE
Auction Table improvements

### ISSUE THREAD

**Issue by alongoni** [gnosis/ido-ux#696]
We can use a table head to reduce the amount of repeated info (see Auction id, Selling, Buying, Status, etc.) 
![image.png](https://images.zenhubusercontent.com/5df949d0b123df159c12ddaa/7e11f956-a0c4-4cbb-b9bf-fe74fa658a8e)

**Comment by cmagan** [comment]
Yeah this was a design decision across the entire app by Gabriel the previous designer.
I'm not opposed to using headers instead of info in each row, but this should be discussed and decided for the entire app IMO

**Comment by alongoni** [comment]
Something like this maybe could work fine: (~40% less text inside the table)
![24- GnosisAuction - Auctions v2 - Table v2](https://user-images.githubusercontent.com/622217/122565534-fa2f5600-d01c-11eb-8953-12147029c26f.png)
Current table design:
![24- GnosisAuction - Auctions v2](https://user-images.githubusercontent.com/622217/122565540-fb608300-d01c-11eb-95c8-d7cdca1f1fea.png)

**Comment by josojo** [comment]
I think it's definitively useful and a good suggestion. 
Not sure about the prior compared to others

wdyt @cmagan

**Comment by cmagan** [comment]
I think the new design is more compact and a bit less dense.
The downside is that the headers are a bit less accessible and you might need to scroll / look at the top to remember what is the column's header. 

To be honest I like the old design but can't really tell why.
Overall in favor of the new proposed design.
I think that if we go with it, it should be implemented on all tables: order table, auction table, landing page table

**Comment by alongoni** [comment]
Thanks! Maybe we can fix the table heading to avoid the need to scroll.
E.g: https://material-ui.com/components/tables/#fixed-header

**Comment by cmagan** [comment]
yes, having fixed header is good idea

**Comment by josojo** [comment]
Yes, I also like the fixed header the best
