### ISSUE TITLE
Add VITA to GA internal token list 

### ISSUE THREAD

**Issue by cmagan** [gnosis/ido-ux#698]
There are to sub tasks. 
One is for testing on rinkeby:
token address: 0x29Db448452e17DC5c50CF5D6e3198b1a531E0D6A
logo: https://ipfs.io/ipfs/QmYmWYViuNG15LghxUhFQbLHKLUvq8Vy3tgJjjvxWJymMG

We're still waiting for them to deploy the mainnet token and then we'd need to add it to the mainnet list.

**Comment by cmagan** [comment]
@hpmaxi I'll let you know once I have the mainnet contract address
In the meantime, if you have it ready to test on test net please ping me on slack :)

**Comment by ramirotw** [comment]
https://github.com/gnosis/ido-ux/pull/700#issuecomment-863959260

> @hpmaxi @josojo
We have the token contract and the logo for the mainnet auction:
0x81f8f0bb1cb2a06649e51913a151f0e7ef6fa321
https://ipfs.io/ipfs/QmYmWYViuNG15LghxUhFQbLHKLUvq8Vy3tgJjjvxWJymMG
