### ISSUE TITLE
Automatic granularity for the orderbook table

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#718]
find a good mechanism that picks the right granularity for auctions.

One could go with mechanisms like:
- Search for a granularity that generates around 20 rows.
- take the current clearing price / 10

but we don't wanna specify it exactly, as we think that you guys will figure out the best option that serves the best UX

**Comment by elena-zh** [comment]
Hey @josojo , 
 what if there are no 20 rows with orders for an auction? How granularity be calculated then?

**Comment by cmagan** [comment]
Then all orders will be displayed individually in its own row...
Not sure 20 rows is the right number...
But def >100 or <5 is either too much or too little information to display

**Comment by ramirotw** [comment]
I'd say that the granularity options as well as the default granularity given an auction should be calculated on the api and not on the browser. We still don't know a proper algorithm with a reasonable complexity that could give us those values without looping many times the bids array and doing too much math. 

On the api this could cached easily without impacting the users. Wdyt?

**Comment by josojo** [comment]
I implemented the logic to take the median /10 and it works nicely for all important auctions. I think it's sufficiently good. 

But even calculating the clearing price on-chain would be performant enough to do it in the front-end. We even do it each time a new order is updated.

What kind of algorithm do you have in mind that we should cache it in the backend?

**Comment by ramirotw** [comment]
> I implemented the logic to take the median /10 and it works nicely for all important auctions. I think it's sufficiently good.

Awesome! I had to take care of my daughter yesterday and couldn't find the time to work on this peacefully.

> What kind of algorithm do you have in mind that we should cache it in the backend?

I was talking about what @cmagan suggested here:

> Not sure 20 rows is the right number...
> But def >100 or <5 is either too much or too little information to display (at least as a default...)

Building the granularity options that satisfy that precondition in a performant way to do it in the browser.
