### ISSUE TITLE
Rounding issues during claiming

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#731]
The following user only got wETH back, which was correct, as his limit price below 0.0004, but the interface is showing him that he would be able to claim VITA
![image.png](https://images.zenhubusercontent.com/5ddee9ea1d3e1600010ad960/17a545ea-23df-4f15-9064-858c62413026)

**Comment by ramirotw** [comment]
@hpmaxi if you have time you can also take a look into this one as the issue could be present in the `useGetAuctionProceeds` that you are currently working on in https://github.com/gnosis/ido-ux/pull/738

**Comment by ramirotw** [comment]
@elena-zh btw could you try to reproduce this issue?

**Comment by elena-zh** [comment]
@ramirotw , not exactly the same behavior, but any odd one I have faced on the Dev env-t. 
Here the auction I have played with: auctionId=214&chainId=4#topAnchor
2 bids: 
 1. 0.0017 DAI with price = 0.0000019999999
 2. 0.0016 DAI with price = 0.000002

Interface showed me correct values to claim: 
1. 0.0017 DAI  and 0 OWL
2. 0 DAI and 800 OWL. 

I run claim transactions and it appeared, that 800 OWL did not appear in a wallet neither for a 1st nor for the 2nd bid:
1. https://rinkeby.etherscan.io/tx/0xa02bede6078d13c080c1897ba9105523a0c883a18fee3efd12076b4fc31f367e
2. https://rinkeby.etherscan.io/tx/0x02a019b15ab2f7b21793ddc0728cccd076541726d9c9e03576c0b28887c1c65c

The case seems to be very similar to the described one as the 2nd bid sees the OWL amount to claim, but received DAI token back. 

Thanks.

**Comment by ramirotw** [comment]
@elena-zh I tried to reproduce again this issue after #738 was merged with  [auction 293](https://ido-ux.dev.gnosisdev.com/#/auction?auctionId=293&chainId=4#topAnchor) but in both claim requests the UI and the tx values were the same.

**Comment by elena-zh** [comment]
@ramirotw , @josojo , I was not able to reproduce the issue

**Comment by josojo** [comment]
Nice, it makes sense that it the situation is improved, as we get more accuracy from the backend.
