### ISSUE TITLE
User is able to claim funds in another supported network

### ISSUE THREAD

**Issue by elena-zh** [gnosis/ido-ux#746]
1. Connect a wallet, 
2. place an order above a current price in an ongoing auction in Rinkeby, as an example
3. wait till the auction ends
4. settle the auction (this step is optional)
5. open auction details page --> claim button is enabled
6. switch to the Mainnet, as an example
7. press on the Claim button

**AR**: claim button is enabled; user is able to rum claim transaction
auction is settled: https://drive.google.com/file/d/1yr2PwrghOgMcSy5m7GqN7w4Qt6gOvbK0/view
auction is not settled: https://drive.google.com/file/d/1aLy4epKKZKcavrLTJ_HqgudG41yeaxCN/view
transaction details https://blockscout.com/poa/xdai/tx/0x22492bb745aae08ef300f847a770226a0e8c263392b3cb63f4e10c4e894dabf0

**ER**: "claim' button is disabled with message 'You had no participation on this auction.' message as soon as user is switched to another network

**Comment by ramirotw** [comment]
Today I'll continue with this issue as I put it on-hold to finish with https://github.com/gnosis/ido-ux/pull/738 andhttps://github.com/gnosis/ido-ux/pull/753

**Comment by elena-zh** [comment]
Here is an additional case that might be related to this issue: claim button is disabled when claim funds under 1st account and then switch to claim funds under another account
![image](https://user-images.githubusercontent.com/70885163/124909002-9f24c980-dff2-11eb-8f39-c41550d28cfe.png)
