### ISSUE TITLE
Create a Media Kit and add it to the docs as a new page

### ISSUE THREAD

**Issue by cmagan** [gnosis/ido-ux#759]
More info on here
https://gnosisinc.slack.com/archives/C01LJGKRJ0L/p1620737267005100

**Comment by alongoni** [comment]
Hey @cmagan I've found this:
https://www.notion.so/Gnosis-Comms-e092358814da46f3833d352f76292c47

Gnosis Auction Media Kit.
https://www.notion.so/Gnosis-Auction-Media-Kit-c6c712821e6c4ad29a2e5736db5c1ff4

**Comment by alongoni** [comment]
@cmagan I made this first draft in Figma, then we can export the logo and variants to import them in the GA Doc's section.
https://www.figma.com/proto/Y7MLpZujRAOFPVkplvA7kV/Gnosis-Auction?node-id=2%3A7435&viewport=75%2C379%2C0.34553584456443787&scaling=min-zoom&page-id=2%3A7434%3Ffuid%3D789860674698606135

I have a question here: Which is the normal logo and which is the variant? In the dApp we are using only the GA logo in white over a dark background and orange as an accent color. It's ok?

**Comment by cmagan** [comment]
thanks @alongoni 
The media kit should have "Built using Gnosis Auction" as the main text
And in smaller text: "The fairest mechanism to auction assets on Ethereum" 
https://docs.google.com/presentation/d/1IuKY_NDEBemvcXB9275d6WfwW9i_59RU7FGyygyPe3g/edit#slide=id.g7a31c7822b_0_151

I think the official logo is the orange one, but it's fine to have also dark / light versions depending on the background

**Comment by cmagan** [comment]
Would you be able to work on this today? @alongoni
