### ISSUE TITLE
The app is crashed when open an auction details page

### ISSUE THREAD

**Issue by elena-zh** [gnosis/ido-ux#760]
The app is crashed when open an auction details page
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/4a091adf-3836-43c3-9e3d-8156be5dd28f)

https://drive.google.com/file/d/1g5bnp1s8EPe3qOMwPoOETTU-4iV-KvOL/view

**Expected**: the app is not crashed

**Comment by josojo** [comment]
Dealing with decimals in the FE is also quite cumbersome. Let me change the behaviour in the backend to provide the values in wei. That should be the best value

**Comment by elena-zh** [comment]
@josojo , seems to be that  values in wei is not a good enough idea.
Look: 
![image](https://user-images.githubusercontent.com/70885163/124602855-f6e7f700-de71-11eb-8b65-95754c1cd01b.png)

Min Funding and Estimated tokens sold calculation: 
auctionId=250&chainId=4
![image](https://user-images.githubusercontent.com/70885163/124599448-593ef880-de6e-11eb-9010-716b1613f46f.png)

auctionId=17&chainId=4
![image](https://user-images.githubusercontent.com/70885163/124599584-8095c580-de6e-11eb-818e-cd043dc7ac7f.png)

Still, the app is crashed when open an ended auctions details 
![image](https://user-images.githubusercontent.com/70885163/124603182-534b1680-de72-11eb-88be-fb0323b2be42.png)

**Comment by elena-zh** [comment]
Hi @josojo !
After the latest deployment of #766 the app works as great!
Besides.. 1 auction: I always get the app crash when I open it (auctionId=17&chainId=4):
![image](https://user-images.githubusercontent.com/70885163/124720000-5d235700-df10-11eb-8645-a3b17d367f81.png)
It might be related to the case then Min funding is tooo low.. or 0?
![image](https://user-images.githubusercontent.com/70885163/124720239-9bb91180-df10-11eb-9bfd-99e6cf68ba17.png)

Could you please take a look at it?

Thanks
