### ISSUE TITLE
Distance between order placing  and order book does not have the correct margin

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#818]
![image](https://user-images.githubusercontent.com/7348154/139558152-e909eefb-498a-4701-ab92-4bc2d899e49a.png)

Expected behaviour: I would love the see more distance between the orderbook component and the order placing component.

**Comment by elena-zh** [comment]
Hey @josojo , it is a duplicate of #796 
@maria-vslvn was trying to tackle it in #763
