### ISSUE TITLE
Polygon: Gas estimation error when place an order

### ISSUE THREAD

**Issue by elena-zh** [gnosis/ido-ux#825]
Auction details: /#/auction?auctionId=10&chainId=137#topAnchor

I'm not able to place an order for the acution die to the gas estimation error
![failed.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0e14d1f4-ebf9-4a73-859d-4a2ebfd19503)
https://watch.screencastify.com/v/zjojaSxrsTKcx0rV9Cfs

**Comment by josojo** [comment]
This needs further ingestigation, though it seems to me that this is an error from the gas estimation within metamask. To which rpc-node are you connected in metamask? https://polygon-rpc.com?

**Comment by elena-zh** [comment]
@josojo , yes

**Comment by josojo** [comment]
@elena-zh is this bug still happening? Or was it something that happend only during a specific time period? I have a hard time figuring out what it was

**Comment by elena-zh** [comment]
@josojo , will retest soon. 
Currently, I have got stuck with pending transactions 
![image](https://user-images.githubusercontent.com/70885163/141463273-c10e9a59-2282-43dd-bf6b-b206f9d12878.png)

**Comment by elena-zh** [comment]
@josojo , the issue still exists
![image](https://user-images.githubusercontent.com/70885163/141466625-45ec0dba-2185-48ec-9495-2b36d91d0efc.png)
auctionId=12&chainId=137#topAnchor
